name: eslint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install module
      run: npm i eslint
    - name: Run ESLint
      run: npx eslint .eslintrc.js
